#!/bin/sh
# Render the Homebrew formula for a released yidam.
#
#   render-formula.sh <version> <checksum-dir> > Formula/yidam.rb
#
# <checksum-dir> holds the `.tar.gz.sha256` files the release workflow packaged —
# one per target, in `shasum -a 256` format. The release job runs this against the
# artifacts it just published and pushes the result to goedelsoup/homebrew-tap.
#
# At the repository root beside `install.sh`, and deliberately not under `dist/`:
# `.gitignore` excludes `dist/` twice over, for Python and for Node build output,
# so a generator placed there is added by no `git add` and the release renders
# nothing. It is the two distribution scripts that belong together anyway.
#
# A SCRIPT and not a heredoc inside the workflow, for one reason: a formula that
# is wrong is only discovered by a stranger running `brew install`, and a
# workflow step is testable only by cutting a release. This is driven by
# `yidam/cli/tests/homebrew_formula.rs` against fixture checksums.
#
# Every target must be present. A formula rendered with a platform missing
# installs fine for everyone else and 404s for exactly the people who cannot
# tell why — so a missing checksum is a hard failure here rather than an
# omitted `on_arm` block.

set -eu

version="${1:-}"
sums="${2:-}"
[ -n "$version" ] && [ -n "$sums" ] || {
  echo "usage: $0 <version> <checksum-dir>" >&2
  exit 2
}

repo="${YIDAM_REPO:-goedelsoup/yidam}"
tag="cli/v$version"
base="https://github.com/$repo/releases/download/$tag"

# The four targets .github/workflows/release.yml builds, in the two shapes
# Homebrew asks about them: on_macos/on_linux × on_arm/on_intel.
sha() {
  file="$sums/yidam-$version-$1.tar.gz.sha256"
  [ -f "$file" ] || { echo "no checksum for $1 at $file" >&2; exit 1; }
  # shasum format is `<hash>  <name>`. Take the hash and check it looks like one:
  # an empty or truncated field renders a formula that fails verification on the
  # user's machine rather than here.
  h=$(awk '{print $1; exit}' "$file")
  case "$h" in
    [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*) ;;
    *) echo "malformed checksum for $1: '$h'" >&2; exit 1 ;;
  esac
  [ "${#h}" -eq 64 ] || { echo "checksum for $1 is ${#h} chars, not 64: '$h'" >&2; exit 1; }
  printf '%s' "$h"
}

mac_arm=$(sha aarch64-apple-darwin)
mac_intel=$(sha x86_64-apple-darwin)
linux_arm=$(sha aarch64-unknown-linux-gnu)
linux_intel=$(sha x86_64-unknown-linux-gnu)

cat <<FORMULA
# typed: false
# frozen_string_literal: true

# GENERATED by render-formula.sh in $repo. Do not edit by hand —
# the next release overwrites this file. Fix the generator instead.
#
# A binary formula, not a source one. The whole point of the tap is to skip a
# compile: the light \`reports\` build is what ships, and \`--features full\`
# (index-build, serve --mcp, the sqlite/rdf exports) remains a source build
# because it needs protoc and an ONNX runtime.
class Yidam < Formula
  desc "Corpus analysis and index CLI for yidam-derived repositories"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/yidam-$version-aarch64-apple-darwin.tar.gz"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/yidam-$version-x86_64-apple-darwin.tar.gz"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/yidam-$version-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/yidam-$version-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_intel"
    end
  end

  # The tarball holds a single \`yidam-<version>-<target>/\` directory, which
  # Homebrew strips on unpack, so the binary and LICENSE are at the staging root.
  def install
    bin.install "yidam"
  end

  # \`--version\` names the version, the build commit, and the compiled feature
  # set. Asserting the version is what catches the failure this formula is most
  # able to cause on its own: a url and a version that disagree, which installs
  # a binary that is not the one the formula claims.
  test do
    assert_match version.to_s, shell_output("#{bin}/yidam --version")
  end
end
FORMULA
