//! `yidam schema` leaves a schema file it did not write where it is (#1057).
//!
//! One derived repository compiles its own, stricter schemas into `.yidam/schemas/` and wires
//! its editor to them. The inherited `mise run schema` overwrote both files with the generic
//! ones, silently, every time somebody ran it — and the repository's answer was a second task
//! file whose only job was to make the inherited task refuse. This is that refusal, moved
//! into the command, where every derived repository gets it without inventing it.
//!
//! Driven through the binary rather than the function: the refusal is an exit code and a
//! stderr, and that is what the task runner and the person see.

use std::path::Path;
use std::process::Command;

mod common;

const PREFIX: &str = "Generated by `yidam schema`";

fn run(dir: &Path, args: &[&str]) -> (String, String, i32) {
    let out = Command::new(env!("CARGO_BIN_EXE_yidam"))
        .current_dir(dir)
        .args(args)
        .output()
        .unwrap();
    (
        String::from_utf8_lossy(&out.stdout).to_string(),
        String::from_utf8_lossy(&out.stderr).to_string(),
        out.status.code().unwrap_or(-1),
    )
}

/// A derived repository an hour after genesis: `.yidam/corpus/` exists and is empty. The
/// five fixed schemas are written; there is no class to compile.
fn bootstrapped() -> tempfile::TempDir {
    let tmp = tempfile::tempdir().unwrap();
    common::git::git(tmp.path(), &["init", "-q"]);
    std::fs::create_dir_all(tmp.path().join(".yidam/corpus")).unwrap();
    tmp
}

fn schemas(root: &Path) -> Vec<(String, String)> {
    let dir = root.join(".yidam/schemas");
    let mut out: Vec<(String, String)> = std::fs::read_dir(&dir)
        .map(|rd| {
            rd.map(|e| e.unwrap().path())
                .filter(|p| p.is_file())
                .map(|p| {
                    (
                        p.file_name().unwrap().to_string_lossy().to_string(),
                        std::fs::read_to_string(&p).unwrap(),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    out.sort();
    out
}

fn comment(text: &str) -> Option<String> {
    serde_json::from_str::<serde_json::Value>(text)
        .ok()?
        .get("$comment")?
        .as_str()
        .map(str::to_string)
}

/// The repository's file, as a generator of its own would write it: valid JSON Schema, no
/// marker, and a `$comment` of its own — the keyword is anyone's to use.
const THEIRS: &str = r#"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$comment": "generated by pnpm --dir web schemas",
  "title": "Ohio education funding — corpus node",
  "type": "object",
  "additionalProperties": false
}
"#;

/// The other half, without which the check could be satisfied by refusing everything: a
/// fresh repository is written, every file is marked, and the second run — the common case,
/// after an `.ont.yml` changed — is not refused by the first run's own output.
#[test]
fn a_fresh_repository_is_written_marked_and_a_second_run_is_not_refused() {
    let d = bootstrapped();
    for _ in 0..2 {
        let (stdout, stderr, code) = run(d.path(), &["schema"]);
        assert_eq!(code, 0, "stdout: {stdout}\nstderr: {stderr}");
    }
    let written = schemas(d.path());
    assert!(!written.is_empty(), "nothing written");
    for (file, text) in &written {
        let c = comment(text).unwrap_or_else(|| panic!("{file} has no $comment"));
        assert!(c.starts_with(PREFIX), "{file}: {c}");
    }
}

/// The failure this file exists for. One target the command did not write refuses the
/// **whole** run: the file it would have replaced is untouched, and the four it could have
/// written beside it are not written either — a partial write is the same failure, smaller.
#[test]
fn a_file_the_command_did_not_write_refuses_the_run_before_anything_is_written() {
    let d = bootstrapped();
    let dir = d.path().join(".yidam/schemas");
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(dir.join("corpus-node.json"), THEIRS).unwrap();

    let (stdout, stderr, code) = run(d.path(), &["schema"]);
    assert_ne!(code, 0, "overwrote a repo-owned schema\nstdout: {stdout}");
    assert!(
        stderr.contains(".yidam/schemas/corpus-node.json"),
        "the refusal must name the file: {stderr}"
    );
    assert!(
        stderr.contains("--force"),
        "the refusal must name the override: {stderr}"
    );
    assert_eq!(
        schemas(d.path()),
        vec![("corpus-node.json".to_string(), THEIRS.to_string())],
        "the directory must hold exactly what it held before"
    );
}

/// Files an earlier release wrote carry no marker either, and the person is the only one
/// who can tell them from the repository's own. `--force` is that answer, given once: after
/// it the files are marked and the next run is ordinary.
#[test]
fn force_replaces_it_and_the_replacement_is_marked() {
    let d = bootstrapped();
    let dir = d.path().join(".yidam/schemas");
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(dir.join("corpus-node.json"), THEIRS).unwrap();

    let (stdout, stderr, code) = run(d.path(), &["schema", "--force"]);
    assert_eq!(code, 0, "stdout: {stdout}\nstderr: {stderr}");
    let written = schemas(d.path());
    assert!(written.len() > 1, "only the one file: {written:?}");
    for (file, text) in &written {
        assert!(
            comment(text).is_some_and(|c| c.starts_with(PREFIX)),
            "{file} unmarked after --force"
        );
    }

    let (_, stderr, code) = run(d.path(), &["schema"]);
    assert_eq!(code, 0, "the run after --force was refused: {stderr}");
}

/// `--settings` reads no schema file and writes none, so a repository that owns its schemas
/// still gets the editor mapping — that mapping is how the repository's own files reach the
/// editor in the first place.
#[test]
fn settings_is_not_refused_over_a_repo_owned_file() {
    let d = bootstrapped();
    let dir = d.path().join(".yidam/schemas");
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(dir.join("corpus-node.json"), THEIRS).unwrap();

    let (stdout, stderr, code) = run(d.path(), &["schema", "--settings"]);
    assert_eq!(code, 0, "{stderr}");
    assert!(stdout.contains("yaml.schemas"), "{stdout}");
    assert_eq!(schemas(d.path()).len(), 1, "--settings wrote a file");
}
