//! Checking the git log against the closed commit vocabulary in `prelude/GRAPH.md`.
//!
//! Separate from the corpus checks because it reads a different thing — history rather
//! than working tree — and because a repository can be perfectly well-formed and still
//! have an illegible log. That is the failure this catches, and it is invisible to every
//! other check here.

use std::path::Path;
use std::process::Command;

use yidam_core::git::is_recognized_verb;

use super::model::{Check, Severity, Violation};

/// One commit's subject, reduced to what the vocabulary cares about.
pub struct Subject {
    pub hash: String,
    pub verb: String,
    pub text: String,
}

/// Read commit subjects, newest first.
///
/// `range` is any git revision range. `None` reads all of history — which for a corpus is
/// usually what you want, since the log *is* the record and its legibility is not a
/// property of the last twenty commits.
pub fn read_subjects(root: &Path, range: Option<&str>) -> Vec<Subject> {
    let mut args = vec!["log".to_string(), "--format=%H%x00%s".to_string()];
    if let Some(r) = range {
        args.push(r.to_string());
    }
    let Ok(out) = Command::new("git").current_dir(root).args(&args).output() else {
        return vec![];
    };
    if !out.status.success() {
        return vec![];
    }
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .filter_map(|line| {
            let (hash, subject) = line.split_once('\0')?;
            Some(Subject {
                hash: hash.to_string(),
                verb: verb_of(subject),
                text: subject.to_string(),
            })
        })
        .collect()
}

/// The leading verb of a subject line, or empty if it has no `verb: ` prefix.
///
/// Matches the parse in `classify_commit` so the two cannot disagree about where the verb
/// ends.
fn verb_of(subject: &str) -> String {
    match subject.find(": ") {
        Some(pos) => subject[..pos].trim().to_string(),
        None => String::new(),
    }
}

/// Merge commits are generated by git, not authored, and `Merge branch 'x'` has no verb.
fn is_merge(subject: &str) -> bool {
    subject.starts_with("Merge branch")
        || subject.starts_with("Merge pull request")
        || subject.starts_with("Merge remote-tracking")
}

pub fn unrecognized_verb(subjects: &[Subject]) -> Check {
    let violations = subjects
        .iter()
        .filter(|s| !is_merge(&s.text))
        .filter(|s| !is_recognized_verb(&s.verb))
        .map(|s| {
            let short = &s.hash[..s.hash.len().min(8)];
            // The hash is already the node; repeating it here would print it twice.
            let detail = if s.verb.is_empty() {
                format!("no `verb: ` prefix — {:?}", truncate(&s.text))
            } else {
                format!("`{}` is not in the vocabulary", s.verb)
            };
            // Identified by commit, not by file: history is immutable, so a baselined
            // entry here stays put and the ratchet gates only what is authored next.
            Violation::new(short, detail)
        })
        .collect();
    Check::new(
        "unrecognized-verb",
        "Commit outside the closed vocabulary",
        Severity::Warn,
        "The commit vocabulary in GRAPH.md is what makes the epistemic/operational split \
         recoverable by anything other than a person reading all of it. An open vocabulary \
         decays into one verb per commit: a repository derived from this template ran ~60 \
         distinct leading words across 100 commits, each evocative and collectively \
         useless. Reported rather than gated, because history cannot be rewritten to fix it \
         — bless the existing log and the ratchet will hold the line from here.",
        violations,
    )
}

fn truncate(s: &str) -> String {
    if s.chars().count() <= 50 {
        return s.to_string();
    }
    format!("{}…", s.chars().take(49).collect::<String>())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn subj(hash: &str, text: &str) -> Subject {
        Subject {
            hash: hash.to_string(),
            verb: verb_of(text),
            text: text.to_string(),
        }
    }

    #[test]
    fn verb_is_the_text_before_the_first_colon_space() {
        assert_eq!(verb_of("establish: a thing"), "establish");
        assert_eq!(verb_of("no verb here"), "");
        // A scope in parentheses is part of the verb token, and is not in the vocabulary.
        assert_eq!(verb_of("fix(cli): a thing"), "fix(cli)");
    }

    #[test]
    fn vocabulary_verbs_pass() {
        let s = vec![
            subj("aaaaaaaa", "establish: confounding as a corpus concept"),
            subj("bbbbbbbb", "extract: 14 permit fields from document Y"),
            subj("cccccccc", "phase: the local half settles"),
        ];
        assert!(unrecognized_verb(&s).passed());
    }

    #[test]
    fn an_invented_verb_is_reported_with_its_hash() {
        let s = vec![subj(
            "deadbeef",
            "viewport: charts that cannot draw a number",
        )];
        let c = unrecognized_verb(&s);
        assert_eq!(c.violations.len(), 1);
        assert_eq!(c.violations[0].node, "deadbeef");
        assert!(c.violations[0].detail.contains("viewport"));
    }

    #[test]
    fn a_subject_with_no_verb_is_reported() {
        let s = vec![subj("deadbeef", "just some words")];
        let c = unrecognized_verb(&s);
        assert_eq!(c.violations.len(), 1);
        assert!(
            c.violations[0].detail.contains("no `verb: ` prefix"),
            "{}",
            c.violations[0].detail
        );
    }

    #[test]
    fn merge_commits_are_exempt() {
        // git authors these; there is no verb to choose.
        let s = vec![
            subj("aaaaaaaa", "Merge branch 'phase/outcome-axis'"),
            subj("bbbbbbbb", "Merge pull request #12 from x/y"),
        ];
        assert!(unrecognized_verb(&s).passed());
    }

    #[test]
    fn the_check_warns_rather_than_gates() {
        // History is immutable; failing on it would wedge every existing repository shut.
        assert_eq!(unrecognized_verb(&[]).severity, Severity::Warn);
    }

    #[test]
    fn a_long_subject_is_truncated_in_the_detail() {
        let long = "x".repeat(200);
        let s = vec![subj("deadbeef", &long)];
        let c = unrecognized_verb(&s);
        assert!(c.violations[0].detail.len() < 120);
    }
}
