//! Which parts of a repository were not authored in it.
//!
//! Checks that read prose walk directories, and a walk cannot tell authored material from
//! material that merely landed there. `broken-prose-link` shipped with the distinction
//! hard-coded to exactly one path — `.yidam/.vendor/` — with a rationale that generalizes
//! perfectly and an implementation that does not:
//!
//! > a defect in the prelude is fixed upstream and adopted by re-vendoring, so reporting one
//! > to a derived repo hands it a finding it cannot act on
//!
//! Measured on a consumer that is not a vendoring repository: **43 broken prose links under
//! `docs/`, 15 of them inside a directory whose own README says it is a frozen, unmodified
//! copy of an upstream project at a fork point.** Editing those to satisfy a linter falsifies
//! the record the directory exists to keep. That repository baselined them and moved on,
//! which is the wrong instrument: a baseline says *we accept this violation*, when the truth
//! is *this file is not ours*. The two decay differently — a baselined entry that is later
//! repaired fails the build by design, so for a frozen import the gate comes to depend on
//! nobody ever re-syncing it.
//!
//! # A claim, not a request for silence
//!
//! Three kinds, and the difference between them is what a reader is owed:
//!
//! - `generated` — written by this repository's own tooling. A defect here is real and it is
//!   the *generator's*. It should fail the generator's tests; reporting it against the file
//!   grades output as though a human wrote it. Requires `by:`, the command that writes it.
//! - `imported` — copied from elsewhere and not modified. A defect here is real and it is
//!   *upstream's*. Requires `from:`, so the record says what it is a copy of.
//! - `excluded` — neither. Requires `why:`.
//!
//! `generated` and `imported` are still scanned and still reported, at info severity,
//! carrying the reason and the address of whoever can act on it. Only `excluded` is silent,
//! and it is named so that a reviewer reading the manifest sees the escape hatch as one.
//!
//! # `.yidam/.vendor/` is an instance and not a special case
//!
//! It is built in, because it is yidam's claim about a directory yidam manages, not something
//! each derived repository should have to restate. Built-in regions are exempt from
//! [`stale`] — a repository is held to what it declared, not to what it inherited.

use std::path::Path;

use anyhow::{Context, Result};
use serde::Deserialize;

/// Where a repository declares what it did not author, relative to its root.
pub const MANIFEST: &str = ".yidam/authorship.yml";

/// How material got here.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    /// Written by this repository's tooling.
    Generated,
    /// Copied from elsewhere, unmodified.
    Imported,
    /// Neither, and not linted.
    Excluded,
}

impl Kind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Kind::Generated => "generated",
            Kind::Imported => "imported",
            Kind::Excluded => "excluded",
        }
    }

    /// Whether findings inside are worth reporting to somebody.
    ///
    /// `excluded` is the only kind that means *do not look*. The other two name a party who
    /// can act — a generator, an upstream — and a finding addressed to them is not noise.
    pub fn reportable(&self) -> bool {
        !matches!(self, Kind::Excluded)
    }
}

/// One declared region of the repository.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Region {
    pub kind: Kind,
    /// Repo-root-relative, without a trailing slash. Matches itself and everything under it.
    pub path: String,
    /// `by:`, `from:` or `why:` — whichever the kind requires.
    pub note: String,
    /// Yidam's own claim about a directory it manages, rather than this repository's.
    pub builtin: bool,
}

impl Region {
    /// Why a finding here is not this repository's to fix, and whose it is.
    pub fn explain(&self) -> String {
        match self.kind {
            Kind::Generated => format!(
                "`{}` is generated by `{}`; the defect is the generator's",
                self.path, self.note
            ),
            Kind::Imported => format!(
                "`{}` is imported unmodified from {}; editing it would falsify the record",
                self.path, self.note
            ),
            Kind::Excluded => format!("`{}` is excluded: {}", self.path, self.note),
        }
    }
}

/// The manifest on the wire. Each kind names its own required field, and unknown fields are
/// rejected: `why:` under `generated:` is a declaration that does not say what it must say,
/// and accepting it silently would make the requirement decorative.
#[derive(Debug, Default, Deserialize)]
#[serde(deny_unknown_fields)]
struct Manifest {
    #[serde(default)]
    generated: Vec<GeneratedEntry>,
    #[serde(default)]
    imported: Vec<ImportedEntry>,
    #[serde(default)]
    excluded: Vec<ExcludedEntry>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct GeneratedEntry {
    path: String,
    /// The command that writes it.
    by: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ImportedEntry {
    path: String,
    /// What this is a copy of.
    from: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ExcludedEntry {
    path: String,
    why: String,
}

/// Trim a declared or scanned path to the form [`Authorship::covering`] compares on.
fn normalize(p: &str) -> String {
    p.replace('\\', "/")
        .trim_start_matches("./")
        .trim_matches('/')
        .to_string()
}

/// Every region of a repository that is not authored in it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Authorship {
    regions: Vec<Region>,
}

impl Default for Authorship {
    /// The built-in regions alone — what a repository with no manifest gets.
    fn default() -> Self {
        Self {
            regions: vec![Region {
                kind: Kind::Imported,
                path: ".yidam/.vendor".to_string(),
                note: "the yidam prelude, adopted by re-vendoring".to_string(),
                builtin: true,
            }],
        }
    }
}

impl Authorship {
    /// Read `.yidam/authorship.yml`, or the built-ins alone if it is absent.
    ///
    /// A manifest that exists and cannot be parsed is an error rather than an empty one.
    /// Degrading to empty would silently re-scan every region it declares, and the flood of
    /// findings would read as a corpus that got worse rather than as a file with a typo.
    pub fn load(root: &Path) -> Result<Self> {
        let path = root.join(MANIFEST);
        if !path.exists() {
            return Ok(Self::default());
        }
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        let manifest: Manifest =
            serde_yaml::from_str(&text).with_context(|| format!("parsing {}", path.display()))?;

        let mut out = Self::default();
        for e in manifest.generated {
            out.regions.push(Region {
                kind: Kind::Generated,
                path: normalize(&e.path),
                note: e.by,
                builtin: false,
            });
        }
        for e in manifest.imported {
            out.regions.push(Region {
                kind: Kind::Imported,
                path: normalize(&e.path),
                note: e.from,
                builtin: false,
            });
        }
        for e in manifest.excluded {
            out.regions.push(Region {
                kind: Kind::Excluded,
                path: normalize(&e.path),
                note: e.why,
                builtin: false,
            });
        }
        Ok(out)
    }

    /// The manifest, or the built-ins if it cannot be read.
    ///
    /// For callers with no error channel — the editor's diagnostics, which must keep
    /// answering while a half-typed manifest is on screen. `lint` uses [`Authorship::load`]
    /// so the typo is reported rather than absorbed.
    pub fn load_or_default(root: &Path) -> Self {
        Self::load(root).unwrap_or_default()
    }

    /// The region covering a repo-relative path, if any.
    ///
    /// Matching is on path components, so `docs/ref` does not cover `docs/reference/`. First
    /// declaration wins when two overlap, which puts the resolution of an overlap in the file
    /// rather than in this function.
    pub fn covering(&self, rel: &str) -> Option<&Region> {
        let rel = normalize(rel);
        self.regions
            .iter()
            .find(|r| rel == r.path || rel.starts_with(&format!("{}/", r.path)))
    }

    /// The regions this repository declared — everything except the built-ins.
    pub fn declared(&self) -> impl Iterator<Item = &Region> {
        self.regions.iter().filter(|r| !r.builtin)
    }
}

/// Declared regions that match nothing on disk.
///
/// A manifest permitted to be wrong drifts, exactly as a lint baseline does, and the entry
/// that outlives the directory it describes is the one that quietly excuses a path somebody
/// later creates with the same name.
///
/// **`generated` is exempt.** Its region is written by a generator and is frequently
/// git-ignored, so on a fresh clone it is absent by construction and the absence carries no
/// information. Holding a repository to it would put the gate's colour on whether anybody had
/// run the build yet.
pub fn stale<'a>(root: &Path, a: &'a Authorship) -> Vec<&'a Region> {
    a.declared()
        .filter(|r| r.kind != Kind::Generated)
        .filter(|r| !root.join(&r.path).exists())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(root: &Path, body: &str) {
        std::fs::create_dir_all(root.join(".yidam")).unwrap();
        std::fs::write(root.join(MANIFEST), body).unwrap();
    }

    #[test]
    fn the_vendor_directory_is_built_in_not_declared() {
        let a = Authorship::default();
        let r = a.covering(".yidam/.vendor/prelude/GRAPH.md").unwrap();
        assert_eq!(r.kind, Kind::Imported);
        assert!(r.builtin);
        // A repository is held to what it declared, and it did not declare this.
        assert_eq!(a.declared().count(), 0);
    }

    #[test]
    fn a_missing_manifest_is_the_built_ins_alone() {
        let tmp = tempfile::tempdir().unwrap();
        assert_eq!(Authorship::load(tmp.path()).unwrap(), Authorship::default());
    }

    #[test]
    fn each_kind_carries_the_field_it_requires() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            tmp.path(),
            "generated:\n  - path: .yidam/reports/\n    by: yidam report\n\
             imported:\n  - path: docs/reference/upstream/\n    from: acme/gis at the fork point\n\
             excluded:\n  - path: docs/scratch/\n    why: working notes\n",
        );
        let a = Authorship::load(tmp.path()).unwrap();
        assert_eq!(a.declared().count(), 3);
        assert_eq!(
            a.covering(".yidam/reports/coverage.md").unwrap().note,
            "yidam report"
        );
        assert_eq!(
            a.covering("docs/scratch/notes.md").unwrap().kind,
            Kind::Excluded
        );
    }

    /// The requirement is the point: a declaration with no addressee is a request for
    /// silence wearing a provenance label.
    #[test]
    fn a_kind_declared_without_its_field_does_not_parse() {
        let tmp = tempfile::tempdir().unwrap();
        write(tmp.path(), "generated:\n  - path: .yidam/reports/\n");
        assert!(Authorship::load(tmp.path()).is_err());
    }

    #[test]
    fn the_wrong_kinds_field_does_not_parse() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            tmp.path(),
            "generated:\n  - path: .yidam/reports/\n    why: it is noisy\n",
        );
        assert!(
            Authorship::load(tmp.path()).is_err(),
            "`why:` under `generated:` names no generator"
        );
    }

    #[test]
    fn a_trailing_slash_and_a_leading_dot_are_the_same_region() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            tmp.path(),
            "excluded:\n  - path: ./docs/scratch/\n    why: notes\n",
        );
        let a = Authorship::load(tmp.path()).unwrap();
        assert!(a.covering("docs/scratch/x.md").is_some());
        assert!(a.covering("docs/scratch").is_some());
    }

    /// The classic prefix bug: `docs/ref` must not swallow `docs/reference/`.
    #[test]
    fn matching_is_on_components_not_bytes() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            tmp.path(),
            "excluded:\n  - path: docs/ref\n    why: notes\n",
        );
        let a = Authorship::load(tmp.path()).unwrap();
        assert!(a.covering("docs/reference/periplus/README.md").is_none());
        assert!(a.covering("docs/ref/README.md").is_some());
    }

    #[test]
    fn the_first_declaration_wins_an_overlap() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            tmp.path(),
            "imported:\n  - path: docs/vendor/\n    from: upstream\n\
             excluded:\n  - path: docs/vendor/deep/\n    why: notes\n",
        );
        let a = Authorship::load(tmp.path()).unwrap();
        assert_eq!(
            a.covering("docs/vendor/deep/x.md").unwrap().kind,
            Kind::Imported
        );
    }

    #[test]
    fn only_excluded_is_silent() {
        assert!(Kind::Generated.reportable());
        assert!(Kind::Imported.reportable());
        assert!(!Kind::Excluded.reportable());
    }

    #[test]
    fn an_unparseable_manifest_is_an_error_not_an_empty_one() {
        let tmp = tempfile::tempdir().unwrap();
        write(tmp.path(), "generated: [oh dear\n");
        assert!(Authorship::load(tmp.path()).is_err());
        // The editor path degrades instead, so diagnostics keep answering mid-edit.
        assert_eq!(
            Authorship::load_or_default(tmp.path()),
            Authorship::default()
        );
    }

    #[test]
    fn a_declared_region_that_matches_nothing_is_stale() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("docs/reference/upstream")).unwrap();
        write(
            tmp.path(),
            "imported:\n  - path: docs/reference/upstream/\n    from: acme/gis\n\
             excluded:\n  - path: docs/gone/\n    why: deleted last year\n",
        );
        let a = Authorship::load(tmp.path()).unwrap();
        let s = stale(tmp.path(), &a);
        assert_eq!(s.len(), 1);
        assert_eq!(s[0].path, "docs/gone");
    }

    /// Absent by construction on a fresh clone — the absence carries no information, so
    /// holding a repository to it would put the gate's colour on whether the build had run.
    #[test]
    fn a_generated_region_is_never_stale_for_being_absent() {
        let tmp = tempfile::tempdir().unwrap();
        write(
            tmp.path(),
            "generated:\n  - path: .yidam/reports/\n    by: yidam report\n",
        );
        let a = Authorship::load(tmp.path()).unwrap();
        assert!(stale(tmp.path(), &a).is_empty());
    }

    /// Yidam's claim, not the repository's: a repo with no vendored prelude has not made a
    /// declaration it can be wrong about.
    #[test]
    fn a_built_in_region_is_never_stale() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(stale(tmp.path(), &Authorship::default()).is_empty());
    }

    #[test]
    fn an_explanation_names_the_party_who_can_act() {
        let g = Region {
            kind: Kind::Generated,
            path: ".yidam/reports".into(),
            note: "yidam report".into(),
            builtin: false,
        };
        assert!(g.explain().contains("the generator's"));
        let i = Region {
            kind: Kind::Imported,
            path: "docs/x".into(),
            note: "acme/gis".into(),
            builtin: false,
        };
        assert!(i.explain().contains("acme/gis"));
    }
}
