//! `yidam migrate routes` — the markers that let a re-vendor reach `AGENTS.md` (#1135).
//!
//! #972 put the reading routes under a generator: `yidam routes` renders
//! `.yidam/.vendor/prelude/routes.yml` into a `<!-- REGEN: yidam routes -->` block. A new
//! derivation gets the block at genesis. An existing one was installed from an older scaffold
//! and has no markers, and [`update_file_regen`](crate::regen::update_file_regen) writes
//! nothing where it finds none. So `yidam regen` is a silent no-op there, and the derivation
//! keeps the whole-file list it was born with. This installs the markers, once.
//!
//! # What it replaces, and what it will not touch
//!
//! The block owns **the bullet list under `## Before taking substantive action`** and nothing
//! else (#969). Across nine derivations on disk, that list held no owner edits and the rest of
//! each `AGENTS.md` was heavily edited. So this finds the heading, finds the first contiguous
//! run of bullets after it, and replaces that run. The heading stays, the prose before the list
//! stays, and the prose after it stays. It does not append: a route at the bottom of the file is
//! a route read last.
//!
//! A bullet that links a vendored prelude file is a hand copy of a template line, however it is
//! worded, and the block now supplies that line. **A bullet that links anything else is an
//! owner's line**, and replacing it would lose it. That refuses, as does a missing heading or a
//! heading with no list under it. Every refusal prints the block, so the owner can paste it where
//! it belongs. A marker is not something to ask a person to hand-write, but a printed one is
//! only copied.
//!
//! It writes the block **rendered**, not a placeholder, so `yidam regen --check` passes on the
//! commit that installs it.

use std::path::Path;

use super::migrate::MigrateReport;

/// The file the block goes into, relative to the repository root.
const FILE: &str = "AGENTS.md";

/// The heading whose list the block replaces.
const HEADING: &str = "## Before taking substantive action";

/// Where every line the block replaces links into.
const VENDORED_LINK: &str = "](.yidam/.vendor/prelude/";

/// The generator's command, as its marker names it.
const COMMAND: &str = "yidam routes";

/// The opening marker, as `sadhana/root/AGENTS.md` writes it.
///
/// **A second copy of the scaffold's, held equal by a test**, for the reason `kuten adopt`
/// gives about its own: the scaffold is consumed at genesis, so an existing repository cannot
/// be handed the marker the way a new one is.
/// [`the_opening_marker_is_the_scaffold_s`](tests) keeps the two from drifting.
const OPEN: &str = "\
<!-- REGEN: yidam routes
Regenerated by: `yidam routes`
Fields: what every occasion reads, each occasion by the commit verbs that end it and the
        sections it reads, then every prelude file whole as reference.
Reads: `.yidam/.vendor/prelude/routes.yml`. Edit the routes there, upstream, never here.
-->";

const CLOSE: &str = "<!-- /REGEN -->";

/// What the migration found in `AGENTS.md`, and what it writes there.
#[derive(Debug, Clone, serde::Serialize)]
pub struct Routes {
    /// Repository-relative. Always `AGENTS.md`.
    pub file: String,
    /// The first line of the list replaced, 1-based. Zero when nothing is replaced.
    pub line: usize,
    /// How many lines of the file the list spans, continuation lines included.
    pub lines: usize,
    /// Each bullet replaced, with its continuation lines joined onto it.
    pub replaced: Vec<String>,
    /// The block, markers included: what is written, or on a refusal what to paste.
    pub block: String,
    /// The file already carries the block, so there is nothing to do.
    pub already: bool,
}

/// Whether `text` carries a `yidam routes` block the generator will find.
///
/// Read by the marker parser `regen` itself uses, and masked first for the reason
/// [`crate::regen::unclaimed_in`] gives: a document that *shows* the marker in a code fence
/// does not carry one.
pub(crate) fn has_block(text: &str) -> bool {
    yidam_core::markers::parse_markers(&crate::markdown::mask_code(text))
        .into_iter()
        .any(|m| matches!(m, yidam_core::markers::Marker::Regen { command, .. } if command == COMMAND))
}

/// The list's extent: the 0-based first line, one past the last, and each bullet joined.
type Run = (usize, usize, Vec<String>);

/// The bullet run under [`HEADING`], or why there is none to replace.
fn locate(text: &str) -> Result<Run, String> {
    let lines: Vec<&str> = text.lines().collect();
    let Some(heading) = lines.iter().position(|l| l.trim_end() == HEADING) else {
        return Err(format!("{FILE} has no `{HEADING}` heading"));
    };
    let mut i = heading + 1;
    while i < lines.len() && !lines[i].starts_with("- ") {
        if lines[i].starts_with('#') {
            break;
        }
        i += 1;
    }
    if i >= lines.len() || !lines[i].starts_with("- ") {
        return Err(format!("no bullet list follows `{HEADING}` in {FILE}"));
    }
    let start = i;
    let mut bullets: Vec<String> = Vec::new();
    while i < lines.len() {
        let line = lines[i];
        if let Some(item) = line.strip_prefix("- ") {
            bullets.push(format!("- {}", item.trim_end()));
        } else if line.starts_with("  ") && !line.trim().is_empty() {
            // A wrapped bullet's continuation. The run starts on a bullet, so there is always
            // one to join it to.
            if let Some(last) = bullets.last_mut() {
                last.push(' ');
                last.push_str(line.trim());
            }
        } else {
            break;
        }
        i += 1;
    }
    Ok((start, i, bullets))
}

/// Plan it. Every refusal goes in `blocked`, and the block to paste goes in `routes`.
pub(crate) fn plan(root: &Path, report: &mut MigrateReport) {
    let path = root.join(FILE);
    let Ok(text) = std::fs::read_to_string(&path) else {
        report.blocked.push(format!(
            "no {FILE} at the repository root, so there is no reading list to route"
        ));
        return;
    };
    let mut routes = Routes {
        file: FILE.to_string(),
        line: 0,
        lines: 0,
        replaced: vec![],
        block: String::new(),
        already: has_block(&text),
    };
    if routes.already {
        report.routes = Some(routes);
        return;
    }
    // Refused rather than written as a placeholder: the list it would replace works today, and
    // a block reading "re-vendor, then run `yidam routes`" would leave the file with none.
    if !root.join(super::routes::VENDORED).exists() {
        report.blocked.push(format!(
            "no `{}` in the vendored prelude, and replacing the list now would leave {FILE} \
             with nothing to read. Re-vendor first: `mise run yidam-vendor-update`",
            super::routes::VENDORED
        ));
        return;
    }
    match super::routes::block(root) {
        Ok(content) => routes.block = format!("{OPEN}\n{content}\n{CLOSE}"),
        Err(e) => {
            report.blocked.push(format!("{e:#}"));
            return;
        }
    }
    match locate(&text) {
        Err(why) => report.blocked.push(why),
        Ok((start, end, bullets)) => {
            for b in &bullets {
                if !b.contains(VENDORED_LINK) {
                    report.blocked.push(format!(
                        "{FILE}:{} links no vendored prelude file, so it is the owner's line \
                         and replacing the list would lose it: {b}",
                        start + 1
                    ));
                }
            }
            routes.line = start + 1;
            routes.lines = end - start;
            routes.replaced = bullets;
        }
    }
    report.routes = Some(routes);
}

/// Write it. Re-derives the list's extent, for the reason `migrate`'s own `apply` re-locates
/// every edit: the plan and the apply are two reads of the same file.
pub(crate) fn apply(root: &Path, report: &mut MigrateReport) -> anyhow::Result<()> {
    let Some(routes) = &report.routes else {
        return Ok(());
    };
    let path = root.join(FILE);
    let text = std::fs::read_to_string(&path)?;
    let (start, end, _) = locate(&text).map_err(anyhow::Error::msg)?;
    let mut lines: Vec<&str> = text.lines().collect();
    lines.splice(start..end, routes.block.lines());
    let mut out = lines.join("\n");
    if text.ends_with('\n') {
        out.push('\n');
    }
    // The whole point is that the generator finds the block. If it would not, the file is left
    // as it was: a written block `regen` cannot see is the silent no-op this exists to end.
    if !has_block(&out) {
        anyhow::bail!("the block written into {FILE} is not one `yidam regen` would find");
    }
    std::fs::write(&path, out)?;
    Ok(())
}

/// One line, for the report once planned.
pub(crate) fn summary(report: &MigrateReport) -> String {
    match &report.routes {
        Some(r) if !r.already => format!(
            "{FILE}'s reading list into the `{COMMAND}` block ({} bullet(s) replaced)",
            r.replaced.len()
        ),
        _ => format!("{FILE}'s reading list into the `{COMMAND}` block"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const DERIVED: &str = "\
# AGENTS.md

## Before taking substantive action

Read the vendored prelude. It is the model this repository runs on, and it is not
negotiable from inside the repo:

- [Identity](.yidam/.vendor/prelude/IDENTITY.md) — what this kind of repository is
- [Agent conduct](.yidam/.vendor/prelude/guidelines/agent-conduct.md) — behavioral norms,
  including the `[verified]` / `[inference]` / `[open]` claim tags
- [Phases](.yidam/.vendor/prelude/PHASES.md) — how a unit of inquiry is bounded and committed

Files under `.yidam/.vendor/` are read-only.

## Conduct norms

- [Not a route](docs/ours.md)
";

    #[test]
    fn the_opening_marker_is_the_scaffold_s() {
        let scaffold = std::fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../sadhana/root/AGENTS.md"),
        )
        .expect("sadhana/root/AGENTS.md is readable");
        assert!(
            scaffold.contains(&format!("{OPEN}\n")),
            "migrate_routes::OPEN is not the marker sadhana/root/AGENTS.md opens its \
             `yidam routes` block with; copy the scaffold's"
        );
    }

    #[test]
    fn the_run_is_the_list_under_the_heading_and_nothing_after_it() {
        let (start, end, bullets) = locate(DERIVED).unwrap();
        let lines: Vec<&str> = DERIVED.lines().collect();
        assert!(lines[start].starts_with("- [Identity]"));
        assert!(lines[end].is_empty(), "the run stops at the blank line");
        assert_eq!(bullets.len(), 3);
        assert!(
            bullets[1].ends_with("behavioral norms, including the `[verified]` / `[inference]` / `[open]` claim tags"),
            "a continuation line joins its bullet: {}",
            bullets[1]
        );
    }

    #[test]
    fn a_heading_with_no_list_before_the_next_heading_has_no_run() {
        let text = "## Before taking substantive action\n\nRead things.\n\n## Next\n\n- [x](y)\n";
        assert!(locate(text).unwrap_err().contains("no bullet list"));
    }

    #[test]
    fn a_missing_heading_has_no_run() {
        assert!(locate("# AGENTS.md\n\n- [x](y)\n")
            .unwrap_err()
            .contains("heading"));
    }

    #[test]
    fn a_block_in_a_code_fence_is_not_carried() {
        let shown = "```\n<!-- REGEN: yidam routes\n-->\nx\n<!-- /REGEN -->\n```\n";
        assert!(!has_block(shown));
        let carried = "<!-- REGEN: yidam routes\n-->\nx\n<!-- /REGEN -->\n";
        assert!(has_block(carried));
    }

    #[test]
    fn a_similarly_named_block_is_not_this_one() {
        assert!(!has_block(
            "<!-- REGEN: yidam routes-old\n-->\nx\n<!-- /REGEN -->\n"
        ));
    }
}
